export type Option = { label: string; value: string; score?: number }
export type Question = {
  id: string
  section: string
  factor: string
  prompt: string
  type: 'mcq' | 'scale' | 'riasec'
  options?: Option[]
  correct?: string
  riasecItems?: { code: 'R'|'I'|'A'|'S'|'E'|'C'; text: string }[]
}

export const questions: Question[] = [
  {id:'Q01',section:'Mathematics',factor:'mathematics',type:'mcq',prompt:'A course costs ₹600. A scholarship covers 20% of the fee. How much does the student have to pay?',correct:'B',options:[{label:'₹420',value:'A'},{label:'₹480',value:'B'},{label:'₹500',value:'C'},{label:'₹520',value:'D'}]},
  {id:'Q02',section:'Mathematics',factor:'mathematics',type:'mcq',prompt:'Three identical machines produce 360 units in 6 hours. At the same rate, how many units would five machines produce in 4 hours?',correct:'B',options:[{label:'360',value:'A'},{label:'400',value:'B'},{label:'480',value:'C'},{label:'500',value:'D'}]},
  {id:'Q03',section:'Mathematics',factor:'mathematics',type:'mcq',prompt:'A student scores 72, 80, 68 and 90 in four tests. What is the average?',correct:'C',options:[{label:'75',value:'A'},{label:'76.5',value:'B'},{label:'77.5',value:'C'},{label:'80',value:'D'}]},
  {id:'Q04',section:'Mathematics',factor:'mathematics',type:'mcq',prompt:'The cost of a project increases from ₹40,000 to ₹50,000. What is the percentage increase?',correct:'C',options:[{label:'10%',value:'A'},{label:'20%',value:'B'},{label:'25%',value:'C'},{label:'30%',value:'D'}]},
  {id:'Q05',section:'Logical Reasoning',factor:'logical_reasoning',type:'mcq',prompt:'Find the next number: 2, 6, 12, 20, 30, ?',correct:'C',options:[{label:'36',value:'A'},{label:'40',value:'B'},{label:'42',value:'C'},{label:'44',value:'D'}]},
  {id:'Q06',section:'Logical Reasoning',factor:'logical_reasoning',type:'mcq',prompt:'Four students A, B, C and D stand in a line. A is before B. C is immediately after D. B is not last. Which arrangement is possible?',correct:'B',options:[{label:'B A D C',value:'A'},{label:'A B D C',value:'B'},{label:'D C B A',value:'C'},{label:'C D A B',value:'D'}]},
  {id:'Q07',section:'Logical Reasoning',factor:'logical_reasoning',type:'mcq',prompt:'Every X is a Y. No Y is a Z. Which statement must be true?',correct:'B',options:[{label:'Some X are Z',value:'A'},{label:'No X is Z',value:'B'},{label:'Every Z is X',value:'C'},{label:'Some Z are Y',value:'D'}]},
  {id:'Q08',section:'Logical Reasoning',factor:'logical_reasoning',type:'mcq',prompt:'Three people must be assigned Design, Coding and Testing. A cannot do Coding. B cannot do Testing. C must do either Design or Testing. Which assignment is possible?',correct:'A',options:[{label:'A = Design, B = Coding, C = Testing',value:'A'},{label:'A = Coding, B = Design, C = Testing',value:'B'},{label:'A = Testing, B = Testing, C = Design',value:'C'},{label:'A = Coding, B = Testing, C = Design',value:'D'}]},
  {id:'Q09',section:'Technical Interest',factor:'technical_interest',type:'mcq',prompt:'Which activity would you most enjoy spending a free afternoon doing?',options:[{label:'Building a small sensor/device or program and figuring out how it works',value:'A',score:100},{label:'Creating a poster or visual design',value:'B',score:60},{label:'Organizing an event',value:'C',score:40},{label:'Writing a story',value:'D',score:20}]},
  {id:'Q10',section:'Technical Interest',factor:'technical_interest',type:'mcq',prompt:'An application keeps crashing. Which activity sounds most interesting to you?',options:[{label:'Reproduce the problem, inspect the logic and try to fix it',value:'A',score:100},{label:'Ask someone else to fix it',value:'B',score:50},{label:'Redesign the appearance of the application',value:'C',score:60},{label:'Stop working on it',value:'D',score:20}]},
  {id:'Q11',section:'Technical Interest',factor:'technical_interest',type:'mcq',prompt:'You receive a new electronic device with no instructions. What would you naturally want to do first?',options:[{label:'Explore how it works and experiment with it',value:'A',score:100},{label:'Change its physical appearance',value:'B',score:60},{label:'Ask someone to explain it',value:'C',score:50},{label:'Put it aside until instructions are available',value:'D',score:20}]},
  {id:'Q12',section:'Creative Problem Solving',factor:'creative_problem_solving',type:'mcq',prompt:'A reusable water bottle keeps leaking. Which part of the problem would you enjoy most?',options:[{label:'Experimenting with different closure designs',value:'A',score:100},{label:'Buying the same type of bottle again',value:'B',score:40},{label:'Asking somebody else what to do',value:'C',score:50},{label:"Following the manufacturer's instructions exactly",value:'D',score:30}]},
  {id:'Q13',section:'Creative Problem Solving',factor:'creative_problem_solving',type:'mcq',prompt:'Your team has only half the original budget for a prototype. What approach appeals to you most?',options:[{label:'Redesign the solution creatively using fewer or cheaper resources',value:'A',score:100},{label:'Use the original design and remove features randomly',value:'B',score:50},{label:'Delay the project',value:'C',score:30},{label:'Wait for someone else to decide',value:'D',score:20}]},
  {id:'Q14',section:'Creative Problem Solving',factor:'creative_problem_solving',type:'mcq',prompt:'Two solutions already work. What would you prefer to do?',options:[{label:'Combine useful ideas from both and test a new approach',value:'A',score:100},{label:'Automatically choose the older solution',value:'B',score:50},{label:'Ask someone else to choose',value:'C',score:40},{label:'Follow whichever solution requires the least thinking',value:'D',score:20}]},
  {id:'Q15',section:'Communication',factor:'communication',type:'mcq',prompt:'You need to explain a technical concept to someone who has never studied it. What would you prefer?',options:[{label:'Use simple language and an example',value:'A',score:100},{label:'Read the technical definition exactly as written',value:'B',score:60},{label:'Tell them to search for it themselves',value:'C',score:30},{label:'Avoid explaining it',value:'D',score:10}]},
  {id:'Q16',section:'Communication',factor:'communication',type:'mcq',prompt:'Two team members strongly disagree about a project decision. What would you naturally do?',options:[{label:'Help both explain their reasoning and work toward a clear decision',value:'A',score:100},{label:'Stay completely silent',value:'B',score:30},{label:'Immediately support whoever speaks first',value:'C',score:50},{label:'Leave the discussion to somebody else',value:'D',score:20}]},
  {id:'Q17',section:'Communication',factor:'communication',type:'mcq',prompt:'Your team has finished a project and must present the result to non-technical judges. Which task sounds most suitable for you?',options:[{label:'Explain the idea, structure the story and answer questions',value:'A',score:100},{label:'Only prepare the code',value:'B',score:50},{label:'Avoid presenting',value:'C',score:20},{label:'Let another person explain everything',value:'D',score:30}]},
  {id:'Q18',section:'Leadership',factor:'leadership',type:'mcq',prompt:'Your team is behind schedule. What would you most naturally do?',options:[{label:'Help divide the remaining work, set priorities and coordinate the team',value:'A',score:100},{label:'Continue only with your own task',value:'B',score:60},{label:'Wait for someone else to take responsibility',value:'C',score:30},{label:'Stop because the deadline looks difficult',value:'D',score:20}]},
  {id:'Q19',section:'Leadership',factor:'leadership',type:'mcq',prompt:'Your team is unsure which approach to use and the deadline is approaching. What would you prefer to do?',options:[{label:'Gather the important information, discuss the options and help the team choose',value:'A',score:100},{label:'Refuse to make any decision',value:'B',score:20},{label:'Choose randomly',value:'C',score:30},{label:'Wait until someone else chooses',value:'D',score:40}]},
  {id:'Q20',section:'Leadership',factor:'leadership',type:'mcq',prompt:'A group project has six people but nobody is coordinating the work. What would you be most comfortable doing?',options:[{label:'Organize responsibilities and make sure everyone knows their task',value:'A',score:100},{label:'Work alone and ignore the coordination problem',value:'B',score:50},{label:'Wait for instructions',value:'C',score:40},{label:'Leave the group',value:'D',score:20}]},
  {id:'Q21',section:'Career Interests',factor:'riasec',type:'riasec',prompt:'Rate your interest from 1–5.',riasecItems:[{code:'R',text:'Building, repairing or physically working with machines/devices'},{code:'I',text:'Investigating why something happens using experiments or data'},{code:'A',text:'Creating original visual or design concepts'}]},
  {id:'Q22',section:'Career Interests',factor:'riasec',type:'riasec',prompt:'Rate your interest from 1–5.',riasecItems:[{code:'S',text:'Teaching, mentoring or helping another person solve a problem'},{code:'E',text:'Pitching an idea, leading an initiative or persuading people'},{code:'C',text:'Organizing information and keeping records/processes accurate'}]},
  {id:'Q23',section:'Career Interests',factor:'riasec',type:'riasec',prompt:'Rate your interest from 1–5.',riasecItems:[{code:'R',text:'Operating tools/equipment and creating practical prototypes'},{code:'I',text:'Analyzing evidence or data to discover an explanation'},{code:'A',text:'Designing a product/interface or visual concept in a new way'}]},
  {id:'Q24',section:'Career Interests',factor:'riasec',type:'riasec',prompt:'Rate your interest from 1–5.',riasecItems:[{code:'S',text:'Explaining something to someone and helping them improve'},{code:'E',text:'Starting a project and motivating people to participate'},{code:'C',text:'Maintaining a structured process and checking information for accuracy'}]},
  {id:'P01',section:'Family Feasibility',factor:'budget',type:'mcq',prompt:'What annual education budget can the family comfortably support?',options:[{label:'Below ₹1 lakh',value:'0.75',score:0},{label:'₹1–2.5 lakh',value:'1.75',score:25},{label:'₹2.5–5 lakh',value:'3.75',score:50},{label:'₹5–10 lakh',value:'7.5',score:75},{label:'Above ₹10 lakh',value:'12',score:100}]},
  {id:'P02',section:'Family Feasibility',factor:'risk_tolerance',type:'scale',prompt:'How comfortable is your family with a career path that has more uncertainty but potentially higher growth?'},
  {id:'P03',section:'Family Feasibility',factor:'location',type:'mcq',prompt:'Where would the family prefer the student to study/work?',options:[{label:'Same city',value:'25',score:25},{label:'Same state',value:'50',score:50},{label:'Anywhere in India',value:'75',score:75},{label:'India or abroad',value:'100',score:100}]},
  {id:'P04',section:'Family Feasibility',factor:'loan_willingness',type:'scale',prompt:'How willing is the family to use an education loan when necessary?'},
  {id:'P05',section:'Family Feasibility',factor:'stability',type:'scale',prompt:'How important is career stability compared with pursuing a high-growth or unconventional path?'}
]

export type Degree = {
  id:string; name:string; short:string; career:string; costLow:number; costHigh:number;
  demand:number; growth:number; salary:number; geography:number; economy:number; resilience:number; disruption:number;
  regions:string[]; skills:string[]; pathway:string;
  weights:number[]; riasec:number[]
}

export const degrees: Degree[] = [
  {id:'D01',name:'B.Tech Computer Science and Engineering',short:'CSE',career:'Software Engineer',costLow:1.5,costHigh:5,demand:88,growth:86,salary:84,geography:90,economy:82,resilience:78,disruption:28,regions:['Bengaluru','Hyderabad','Chennai','Pune'],skills:['Programming','DSA','Databases','Software design'],pathway:'B.Tech CSE → internships/projects → software/data/cloud roles',weights:[18,20,22,10,10,5,15],riasec:[8,40,5,5,12,30]},
  {id:'D02',name:'B.Tech Artificial Intelligence and Data Science',short:'AI & DS',career:'AI/ML Engineer',costLow:1.8,costHigh:5.5,demand:92,growth:95,salary:90,geography:88,economy:84,resilience:81,disruption:30,regions:['Bengaluru','Hyderabad','Chennai','Pune'],skills:['Python','Statistics','Machine learning','Data engineering'],pathway:'B.Tech AI/DS → ML/data projects → AI, analytics and data roles',weights:[25,22,20,8,5,5,15],riasec:[5,50,5,5,10,25]},
  {id:'D03',name:'B.Tech Information Technology',short:'IT',career:'Cloud/DevOps Engineer',costLow:1.5,costHigh:4.8,demand:85,growth:84,salary:82,geography:88,economy:82,resilience:80,disruption:27,regions:['Bengaluru','Chennai','Hyderabad','Pune'],skills:['Networking','Cloud','Web systems','Databases'],pathway:'B.Tech IT → systems/cloud/web exposure → IT and platform roles',weights:[12,18,24,12,14,5,15],riasec:[5,30,8,10,12,35]},
  {id:'D04',name:'B.Tech Electronics and Communication Engineering',short:'ECE',career:'Software Engineer',costLow:1.5,costHigh:5,demand:78,growth:82,salary:76,geography:80,economy:79,resilience:83,disruption:24,regions:['Bengaluru','Chennai','Hyderabad','Noida'],skills:['Circuits','Embedded systems','Signal processing','Programming'],pathway:'B.Tech ECE → embedded/VLSI/communications/software specialization',weights:[20,18,20,12,10,5,15],riasec:[25,35,5,5,10,20]},
  {id:'D05',name:'B.Tech Electrical and Electronics Engineering',short:'EEE',career:'Software Engineer',costLow:1.4,costHigh:4.8,demand:76,growth:78,salary:72,geography:78,economy:80,resilience:87,disruption:20,regions:['Chennai','Bengaluru','Pune','Hyderabad'],skills:['Power systems','Control','Electronics','Simulation'],pathway:'B.Tech EEE → power/control/electronics/EV/automation roles',weights:[22,18,18,10,10,5,17],riasec:[25,35,5,5,10,20]},
  {id:'D06',name:'B.Tech Mechanical Engineering',short:'Mechanical',career:'Mechanical Engineer',costLow:1.3,costHigh:4.5,demand:74,growth:76,salary:69,geography:77,economy:80,resilience:86,disruption:19,regions:['Chennai','Pune','Bengaluru','Gurugram'],skills:['CAD','Manufacturing','Thermal systems','Mechanics'],pathway:'B.Tech Mechanical → CAD/manufacturing/automotive/energy specialization',weights:[18,18,18,15,10,5,16],riasec:[35,30,8,5,7,15]},
  {id:'D07',name:'B.Tech Civil Engineering',short:'Civil',career:'Mechanical Engineer',costLow:1.2,costHigh:4.2,demand:72,growth:74,salary:65,geography:75,economy:78,resilience:90,disruption:14,regions:['Chennai','Bengaluru','Mumbai','Delhi NCR'],skills:['Structures','Surveying','CAD/BIM','Project management'],pathway:'B.Tech Civil → site/design/BIM/infrastructure/project roles',weights:[15,15,12,15,15,10,18],riasec:[35,20,8,10,12,15]},
  {id:'D08',name:'B.Tech Chemical Engineering',short:'Chemical',career:'Data Scientist',costLow:1.4,costHigh:4.6,demand:70,growth:71,salary:72,geography:68,economy:79,resilience:88,disruption:18,regions:['Gujarat','Mumbai','Chennai','Hyderabad'],skills:['Process design','Thermodynamics','Safety','Simulation'],pathway:'B.Tech Chemical → process/energy/materials/pharma specialization',weights:[20,17,15,14,10,5,19],riasec:[20,40,5,10,5,20]},
  {id:'D09',name:'B.Tech Biotechnology',short:'Biotechnology',career:'Data Scientist',costLow:1.5,costHigh:4.8,demand:73,growth:82,salary:68,geography:70,economy:78,resilience:91,disruption:12,regions:['Hyderabad','Bengaluru','Pune','Chennai'],skills:['Biology','Lab methods','Bioinformatics','Data analysis'],pathway:'B.Tech Biotechnology → biotech/lab/bioinformatics/higher-study pathways',weights:[15,15,10,15,15,5,25],riasec:[15,45,5,20,5,10]},
  {id:'D10',name:'B.Tech Biomedical Engineering',short:'Biomedical',career:'Data Scientist',costLow:1.5,costHigh:5,demand:75,growth:84,salary:70,geography:72,economy:79,resilience:92,disruption:11,regions:['Bengaluru','Hyderabad','Chennai','Mumbai'],skills:['Medical devices','Signals','Electronics','Biology'],pathway:'B.Tech Biomedical → devices/imaging/clinical engineering/data roles',weights:[18,17,12,15,13,5,20],riasec:[15,40,5,25,5,10]}
]
